# Generated by Django 4.2.1 on 2023-12-21 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='DeadLine',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
